In [9]:
from google.colab import files

# Upload file manually
uploaded = files.upload()

Saving cyber.csv to cyber (1).csv

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv("cyber.csv", encoding='latin-1', delimiter=',', on_bad_lines='skip')

In [14]:
print(df.columns)

Index(['AttackDate;Country;Spam;Ransomware;Local Infection;Exploit;Malicious Mail;Network Attack;On Demand Scan;Web Threat;Total_Attack_Percentage;Rank Spam;Rank Ransomware;Rank Local Infection;Rank Exploit;Rank Malicious Mail;Rank Network Attack;Rank On Demand Scan;Rank Web Threat'], dtype='object')

In [15]:
df

      AttackDate;Country;Spam;Ransomware;Local Infection;Exploit;Malicious Mail;Network Attack;On Demand Scan;Web Threat;Total_Attack_Percentage;Rank Spam;Rank Ransomware;Rank Local Infection;Rank Exploit;Rank Malicious Mail;Rank Network Attack;Rank On Demand Scan;Rank Web Threat
0      2022-10-11 00:00:00;Arab Republic of Egypt;0.0...
1      2022-10-11 00:00:00;Argentine Republic;0.00601...
2      2022-10-11 00:00:00;Aruba;;;0.01384;;0.00092;;...
3      2022-10-11 00:00:00;Bailiwick of Guernsey;;;0....
4      2022-10-11 00:00:00;Bailiwick of Jersey;0.0000...
...                                                  ...
77226  2023-12-11 00:00:00;United Arab Emirates;0.000...
77227  2023-12-11 00:00:00;United Kingdom of Great Br...
77228  2023-12-11 00:00:00;United Mexican States;0.00...
77229  2023-12-11 00:00:00;United Republic of Tanzani...
77230  2023-12-11 00:00:00;United States of America;0...

[77231 rows x 1 columns]

In [17]:
df = pd.read_csv('cyber.csv', sep=';', encoding='latin-1')
# or 'ISO-8859-1', or any other encoding that might be appropriate for your file.

In [18]:
df

,AttackDate,Country,Spam,Ransomware,Local Infection,Exploit,Malicious Mail,Network Attack,On Demand Scan,Web Threat,Total_Attack_Percentage,Rank Spam,Rank Ransomware,Rank Local Infection,Rank Exploit,Rank Malicious Mail,Rank Network Attack,Rank On Demand Scan,Rank Web Threat
0,2022-10-11 00:00:00,Arab Republic of Egypt,0.00090,0.00013,0.01353,0.00013,0.00287,0.01007,0.01148,0.01708,0.007024,68,47,85,176,34,11,78,53
1,2022-10-11 00:00:00,Argentine Republic,0.00601,0.00006,0.00575,0.00035,0.00058,0.00095,0.00482,0.00974,0.003533,27,86,174,128,140,138,174,160
2,2022-10-11 00:00:00,Aruba,NaN,NaN,0.01384,NaN,0.00092,NaN,0.00830,0.00554,0.007150,162,143,82,186,104,187,119,190
3,2022-10-11 00:00:00,Bailiwick of Guernsey,NaN,NaN,0.00546,0.00273,NaN,0.00091,0.00546,0.01001,0.004914,162,143,179,1,186,141,164,159
4,2022-10-11 00:00:00,Bailiwick of Jersey,0.00003,NaN,0.00774,0.00101,0.00067,NaN,0.00707,0.01145,0.004662,138,143,150,31,133,187,137,146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77618,2023-12-11 00:00:00,United Arab Emirates,0.00064,0.00009,0.00901,0.00057,0.00198,0.00149,0.00892,0.01274,0.004430,86,37,100,43,2,40,42,87
77619,2023-12-11 00:00:00,United Kingdom of Great Britain and Northern I...,0.01292,0.00003,0.00428,0.00084,0.00021,0.00045,0.00382,0.01205,0.004325,12,89,173,14,97,139,171,100
77620,2023-12-11 00:00:00,United Mexican States,0.00500,0.00004,0.00870,0.00019,0.00035,0.00106,0.00772,0.00834,0.003925,34,77,106,122,65,68,74,152
77621,2023-12-11 00:00:00,United Republic of Tanzania,0.00030,0.00002,0.01201,0.00031,0.00028,0.00091,0.00717,0.01145,0.004056,101,116,54,83,77,83,92,114
77622,2023-12-11 00:00:00,United States of America,0.21790,0.00003,0.00634,0.00163,0.00020,0.00111,0.00578,0.00906,0.030256,1,89,139,2,101,64,125,143

In [19]:
df['AttackDate'] = pd.to_datetime(df['AttackDate'], format='%Y-%m-%d %H:%M:%S')

In [20]:
print(df.head())

  AttackDate                 Country     Spam  Ransomware  Local Infection  \
0 2022-10-11  Arab Republic of Egypt  0.00090     0.00013          0.01353
1 2022-10-11      Argentine Republic  0.00601     0.00006          0.00575
2 2022-10-11                   Aruba      NaN         NaN          0.01384
3 2022-10-11   Bailiwick of Guernsey      NaN         NaN          0.00546
4 2022-10-11     Bailiwick of Jersey  0.00003         NaN          0.00774

   Exploit  Malicious Mail  Network Attack  On Demand Scan  Web Threat  \
0  0.00013         0.00287         0.01007         0.01148     0.01708
1  0.00035         0.00058         0.00095         0.00482     0.00974
2      NaN         0.00092             NaN         0.00830     0.00554
3  0.00273             NaN         0.00091         0.00546     0.01001
4  0.00101         0.00067             NaN         0.00707     0.01145

   Total_Attack_Percentage  Rank Spam  Rank Ransomware  Rank Local Infection  \
0                 0.007024         68               47                    85
1                 0.003533         27               86                   174
2                 0.007150        162              143                    82
3                 0.004914        162              143                   179
4                 0.004662        138              143                   150

   Rank Exploit  Rank Malicious Mail  Rank Network Attack  \
0           176                   34                   11
1           128                  140                  138
2           186                  104                  187
3             1                  186                  141
4            31                  133                  187

   Rank On Demand Scan  Rank Web Threat
0                   78               53
1                  174              160
2                  119              190
3                  164              159
4                  137              146

In [21]:
df

,AttackDate,Country,Spam,Ransomware,Local Infection,Exploit,Malicious Mail,Network Attack,On Demand Scan,Web Threat,Total_Attack_Percentage,Rank Spam,Rank Ransomware,Rank Local Infection,Rank Exploit,Rank Malicious Mail,Rank Network Attack,Rank On Demand Scan,Rank Web Threat
0,2022-10-11,Arab Republic of Egypt,0.00090,0.00013,0.01353,0.00013,0.00287,0.01007,0.01148,0.01708,0.007024,68,47,85,176,34,11,78,53
1,2022-10-11,Argentine Republic,0.00601,0.00006,0.00575,0.00035,0.00058,0.00095,0.00482,0.00974,0.003533,27,86,174,128,140,138,174,160
2,2022-10-11,Aruba,NaN,NaN,0.01384,NaN,0.00092,NaN,0.00830,0.00554,0.007150,162,143,82,186,104,187,119,190
3,2022-10-11,Bailiwick of Guernsey,NaN,NaN,0.00546,0.00273,NaN,0.00091,0.00546,0.01001,0.004914,162,143,179,1,186,141,164,159
4,2022-10-11,Bailiwick of Jersey,0.00003,NaN,0.00774,0.00101,0.00067,NaN,0.00707,0.01145,0.004662,138,143,150,31,133,187,137,146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77618,2023-12-11,United Arab Emirates,0.00064,0.00009,0.00901,0.00057,0.00198,0.00149,0.00892,0.01274,0.004430,86,37,100,43,2,40,42,87
77619,2023-12-11,United Kingdom of Great Britain and Northern I...,0.01292,0.00003,0.00428,0.00084,0.00021,0.00045,0.00382,0.01205,0.004325,12,89,173,14,97,139,171,100
77620,2023-12-11,United Mexican States,0.00500,0.00004,0.00870,0.00019,0.00035,0.00106,0.00772,0.00834,0.003925,34,77,106,122,65,68,74,152
77621,2023-12-11,United Republic of Tanzania,0.00030,0.00002,0.01201,0.00031,0.00028,0.00091,0.00717,0.01145,0.004056,101,116,54,83,77,83,92,114
77622,2023-12-11,United States of America,0.21790,0.00003,0.00634,0.00163,0.00020,0.00111,0.00578,0.00906,0.030256,1,89,139,2,101,64,125,143

In [23]:
print(df['Spam'].isnull().sum())  # Count missing values

14641

In [24]:
df['Spam'].fillna(df['Spam'].mean(), inplace=True)  # Replace with mean

<ipython-input-24-6f19c1df1ef9>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Spam'].fillna(df['Spam'].mean(), inplace=True)  # Replace with mean

In [25]:
df

,AttackDate,Country,Spam,Ransomware,Local Infection,Exploit,Malicious Mail,Network Attack,On Demand Scan,Web Threat,Total_Attack_Percentage,Rank Spam,Rank Ransomware,Rank Local Infection,Rank Exploit,Rank Malicious Mail,Rank Network Attack,Rank On Demand Scan,Rank Web Threat
0,2022-10-11,Arab Republic of Egypt,0.000900,0.00013,0.01353,0.00013,0.00287,0.01007,0.01148,0.01708,0.007024,68,47,85,176,34,11,78,53
1,2022-10-11,Argentine Republic,0.006010,0.00006,0.00575,0.00035,0.00058,0.00095,0.00482,0.00974,0.003533,27,86,174,128,140,138,174,160
2,2022-10-11,Aruba,0.006094,NaN,0.01384,NaN,0.00092,NaN,0.00830,0.00554,0.007150,162,143,82,186,104,187,119,190
3,2022-10-11,Bailiwick of Guernsey,0.006094,NaN,0.00546,0.00273,NaN,0.00091,0.00546,0.01001,0.004914,162,143,179,1,186,141,164,159
4,2022-10-11,Bailiwick of Jersey,0.000030,NaN,0.00774,0.00101,0.00067,NaN,0.00707,0.01145,0.004662,138,143,150,31,133,187,137,146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77618,2023-12-11,United Arab Emirates,0.000640,0.00009,0.00901,0.00057,0.00198,0.00149,0.00892,0.01274,0.004430,86,37,100,43,2,40,42,87
77619,2023-12-11,United Kingdom of Great Britain and Northern I...,0.012920,0.00003,0.00428,0.00084,0.00021,0.00045,0.00382,0.01205,0.004325,12,89,173,14,97,139,171,100
77620,2023-12-11,United Mexican States,0.005000,0.00004,0.00870,0.00019,0.00035,0.00106,0.00772,0.00834,0.003925,34,77,106,122,65,68,74,152
77621,2023-12-11,United Republic of Tanzania,0.000300,0.00002,0.01201,0.00031,0.00028,0.00091,0.00717,0.01145,0.004056,101,116,54,83,77,83,92,114
77622,2023-12-11,United States of America,0.217900,0.00003,0.00634,0.00163,0.00020,0.00111,0.00578,0.00906,0.030256,1,89,139,2,101,64,125,143

In [26]:
print(df['Ransomware'].isnull().sum())  # Count missing values

25479

In [27]:
df['Ransomware'].fillna(0, inplace=True)

<ipython-input-27-48fe46e60800>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Ransomware'].fillna(0, inplace=True)

In [28]:
print(df['Local Infection'].isnull().sum())  # Count missing values

3154

In [29]:
df['Local Infection'].fillna(0, inplace=True)

<ipython-input-29-c1c791aff686>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Local Infection'].fillna(0, inplace=True)

In [30]:
df

,AttackDate,Country,Spam,Ransomware,Local Infection,Exploit,Malicious Mail,Network Attack,On Demand Scan,Web Threat,Total_Attack_Percentage,Rank Spam,Rank Ransomware,Rank Local Infection,Rank Exploit,Rank Malicious Mail,Rank Network Attack,Rank On Demand Scan,Rank Web Threat
0,2022-10-11,Arab Republic of Egypt,0.000900,0.00013,0.01353,0.00013,0.00287,0.01007,0.01148,0.01708,0.007024,68,47,85,176,34,11,78,53
1,2022-10-11,Argentine Republic,0.006010,0.00006,0.00575,0.00035,0.00058,0.00095,0.00482,0.00974,0.003533,27,86,174,128,140,138,174,160
2,2022-10-11,Aruba,0.006094,0.00000,0.01384,NaN,0.00092,NaN,0.00830,0.00554,0.007150,162,143,82,186,104,187,119,190
3,2022-10-11,Bailiwick of Guernsey,0.006094,0.00000,0.00546,0.00273,NaN,0.00091,0.00546,0.01001,0.004914,162,143,179,1,186,141,164,159
4,2022-10-11,Bailiwick of Jersey,0.000030,0.00000,0.00774,0.00101,0.00067,NaN,0.00707,0.01145,0.004662,138,143,150,31,133,187,137,146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77618,2023-12-11,United Arab Emirates,0.000640,0.00009,0.00901,0.00057,0.00198,0.00149,0.00892,0.01274,0.004430,86,37,100,43,2,40,42,87
77619,2023-12-11,United Kingdom of Great Britain and Northern I...,0.012920,0.00003,0.00428,0.00084,0.00021,0.00045,0.00382,0.01205,0.004325,12,89,173,14,97,139,171,100
77620,2023-12-11,United Mexican States,0.005000,0.00004,0.00870,0.00019,0.00035,0.00106,0.00772,0.00834,0.003925,34,77,106,122,65,68,74,152
77621,2023-12-11,United Republic of Tanzania,0.000300,0.00002,0.01201,0.00031,0.00028,0.00091,0.00717,0.01145,0.004056,101,116,54,83,77,83,92,114
77622,2023-12-11,United States of America,0.217900,0.00003,0.00634,0.00163,0.00020,0.00111,0.00578,0.00906,0.030256,1,89,139,2,101,64,125,143

In [31]:
print(df['Exploit'].isnull().sum())  # Count missing values

13359

In [32]:
df['Exploit'].fillna(0, inplace=True)

<ipython-input-32-8f8f75d8f816>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Exploit'].fillna(0, inplace=True)

In [33]:
print(df['Malicious Mail'].isnull().sum())  # Count missing values

8439

In [35]:
df['Malicious Mail'].fillna(0, inplace=True)

<ipython-input-35-a812375bb152>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Malicious Mail'].fillna(0, inplace=True)

In [36]:
print(df['Network Attack'].isnull().sum())  # Count missing values

6091

In [37]:
df['Network Attack'].fillna(df['Network Attack'].mean(), inplace=True)

<ipython-input-37-bfe3a899efc3>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Network Attack'].fillna(df['Network Attack'].mean(), inplace=True)

In [38]:
print(df['On Demand Scan'].isnull().sum())  # Count missing values

3392

In [41]:
print(df['Web Threat'].isnull().sum())  # Count missing values

3731

In [44]:
print(df['Rank Spam'].isnull().sum())  # Count missing values

0

In [45]:
df

,AttackDate,Country,Spam,Ransomware,Local Infection,Exploit,Malicious Mail,Network Attack,On Demand Scan,Web Threat,Total_Attack_Percentage,Rank Spam,Rank Ransomware,Rank Local Infection,Rank Exploit,Rank Malicious Mail,Rank Network Attack,Rank On Demand Scan,Rank Web Threat
0,2022-10-11,Arab Republic of Egypt,0.000900,0.00013,0.01353,0.00013,0.00287,0.010070,0.01148,0.01708,0.007024,68,47,85,176,34,11,78,53
1,2022-10-11,Argentine Republic,0.006010,0.00006,0.00575,0.00035,0.00058,0.000950,0.00482,0.00974,0.003533,27,86,174,128,140,138,174,160
2,2022-10-11,Aruba,0.006094,0.00000,0.01384,0.00000,0.00092,0.002222,0.00830,0.00554,0.007150,162,143,82,186,104,187,119,190
3,2022-10-11,Bailiwick of Guernsey,0.006094,0.00000,0.00546,0.00273,0.00000,0.000910,0.00546,0.01001,0.004914,162,143,179,1,186,141,164,159
4,2022-10-11,Bailiwick of Jersey,0.000030,0.00000,0.00774,0.00101,0.00067,0.002222,0.00707,0.01145,0.004662,138,143,150,31,133,187,137,146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77618,2023-12-11,United Arab Emirates,0.000640,0.00009,0.00901,0.00057,0.00198,0.001490,0.00892,0.01274,0.004430,86,37,100,43,2,40,42,87
77619,2023-12-11,United Kingdom of Great Britain and Northern I...,0.012920,0.00003,0.00428,0.00084,0.00021,0.000450,0.00382,0.01205,0.004325,12,89,173,14,97,139,171,100
77620,2023-12-11,United Mexican States,0.005000,0.00004,0.00870,0.00019,0.00035,0.001060,0.00772,0.00834,0.003925,34,77,106,122,65,68,74,152
77621,2023-12-11,United Republic of Tanzania,0.000300,0.00002,0.01201,0.00031,0.00028,0.000910,0.00717,0.01145,0.004056,101,116,54,83,77,83,92,114
77622,2023-12-11,United States of America,0.217900,0.00003,0.00634,0.00163,0.00020,0.001110,0.00578,0.00906,0.030256,1,89,139,2,101,64,125,143

In [42]:
df['Web Threat'].fillna(0, inplace=True)

<ipython-input-42-3640d5c76317>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Web Threat'].fillna(0, inplace=True)

In [43]:
df['Total_Attack_Percentage'].fillna(df['Total_Attack_Percentage'].mean(), inplace=True)

<ipython-input-43-8b20d1127c12>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Total_Attack_Percentage'].fillna(df['Total_Attack_Percentage'].mean(), inplace=True)

In [39]:
df['On Demand Scan'].fillna(0, inplace=True)

<ipython-input-39-8790c755cdf4>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['On Demand Scan'].fillna(0, inplace=True)

In [40]:
df

,AttackDate,Country,Spam,Ransomware,Local Infection,Exploit,Malicious Mail,Network Attack,On Demand Scan,Web Threat,Total_Attack_Percentage,Rank Spam,Rank Ransomware,Rank Local Infection,Rank Exploit,Rank Malicious Mail,Rank Network Attack,Rank On Demand Scan,Rank Web Threat
0,2022-10-11,Arab Republic of Egypt,0.000900,0.00013,0.01353,0.00013,0.00287,0.010070,0.01148,0.01708,0.007024,68,47,85,176,34,11,78,53
1,2022-10-11,Argentine Republic,0.006010,0.00006,0.00575,0.00035,0.00058,0.000950,0.00482,0.00974,0.003533,27,86,174,128,140,138,174,160
2,2022-10-11,Aruba,0.006094,0.00000,0.01384,0.00000,0.00092,0.002222,0.00830,0.00554,0.007150,162,143,82,186,104,187,119,190
3,2022-10-11,Bailiwick of Guernsey,0.006094,0.00000,0.00546,0.00273,0.00000,0.000910,0.00546,0.01001,0.004914,162,143,179,1,186,141,164,159
4,2022-10-11,Bailiwick of Jersey,0.000030,0.00000,0.00774,0.00101,0.00067,0.002222,0.00707,0.01145,0.004662,138,143,150,31,133,187,137,146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77618,2023-12-11,United Arab Emirates,0.000640,0.00009,0.00901,0.00057,0.00198,0.001490,0.00892,0.01274,0.004430,86,37,100,43,2,40,42,87
77619,2023-12-11,United Kingdom of Great Britain and Northern I...,0.012920,0.00003,0.00428,0.00084,0.00021,0.000450,0.00382,0.01205,0.004325,12,89,173,14,97,139,171,100
77620,2023-12-11,United Mexican States,0.005000,0.00004,0.00870,0.00019,0.00035,0.001060,0.00772,0.00834,0.003925,34,77,106,122,65,68,74,152
77621,2023-12-11,United Republic of Tanzania,0.000300,0.00002,0.01201,0.00031,0.00028,0.000910,0.00717,0.01145,0.004056,101,116,54,83,77,83,92,114
77622,2023-12-11,United States of America,0.217900,0.00003,0.00634,0.00163,0.00020,0.001110,0.00578,0.00906,0.030256,1,89,139,2,101,64,125,143

In [46]:
print(df['Rank Ransomware'].isnull().sum())  # Count missing values

0

In [ ]:
print(df['Web Threat'].isnull().sum())  # Count missing values

In [47]:
print(df['Rank Local Infection'].isnull().sum())  # Count missing values

0

In [48]:
print(df['Rank Exploit'].isnull().sum())  # Count missing values

0

In [49]:
print(df['Rank Malicious Mail'].isnull().sum())  # Count missing values

0

In [50]:
print(df['Rank Network Attack'].isnull().sum())  # Count missing values

0

In [51]:
print(df['Rank On Demand Scan'].isnull().sum())  # Count missing values

0

In [52]:
print(df['Rank Web Threat'].isnull().sum())  # Count missing values

0

In [53]:
df['Total_Attack_Percentage'] = df['Total_Attack_Percentage'] * 100
df['Total_Attack_Percentage'] = df['Total_Attack_Percentage'].map(lambda x: f"{x:.2f}%")

In [54]:
df

,AttackDate,Country,Spam,Ransomware,Local Infection,Exploit,Malicious Mail,Network Attack,On Demand Scan,Web Threat,Total_Attack_Percentage,Rank Spam,Rank Ransomware,Rank Local Infection,Rank Exploit,Rank Malicious Mail,Rank Network Attack,Rank On Demand Scan,Rank Web Threat
0,2022-10-11,Arab Republic of Egypt,0.000900,0.00013,0.01353,0.00013,0.00287,0.010070,0.01148,0.01708,0.70%,68,47,85,176,34,11,78,53
1,2022-10-11,Argentine Republic,0.006010,0.00006,0.00575,0.00035,0.00058,0.000950,0.00482,0.00974,0.35%,27,86,174,128,140,138,174,160
2,2022-10-11,Aruba,0.006094,0.00000,0.01384,0.00000,0.00092,0.002222,0.00830,0.00554,0.71%,162,143,82,186,104,187,119,190
3,2022-10-11,Bailiwick of Guernsey,0.006094,0.00000,0.00546,0.00273,0.00000,0.000910,0.00546,0.01001,0.49%,162,143,179,1,186,141,164,159
4,2022-10-11,Bailiwick of Jersey,0.000030,0.00000,0.00774,0.00101,0.00067,0.002222,0.00707,0.01145,0.47%,138,143,150,31,133,187,137,146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77618,2023-12-11,United Arab Emirates,0.000640,0.00009,0.00901,0.00057,0.00198,0.001490,0.00892,0.01274,0.44%,86,37,100,43,2,40,42,87
77619,2023-12-11,United Kingdom of Great Britain and Northern I...,0.012920,0.00003,0.00428,0.00084,0.00021,0.000450,0.00382,0.01205,0.43%,12,89,173,14,97,139,171,100
77620,2023-12-11,United Mexican States,0.005000,0.00004,0.00870,0.00019,0.00035,0.001060,0.00772,0.00834,0.39%,34,77,106,122,65,68,74,152
77621,2023-12-11,United Republic of Tanzania,0.000300,0.00002,0.01201,0.00031,0.00028,0.000910,0.00717,0.01145,0.41%,101,116,54,83,77,83,92,114
77622,2023-12-11,United States of America,0.217900,0.00003,0.00634,0.00163,0.00020,0.001110,0.00578,0.00906,3.03%,1,89,139,2,101,64,125,143

In [55]:
duplicates = df[df.duplicated()]
print(duplicates)

Empty DataFrame
Columns: [AttackDate, Country, Spam, Ransomware, Local Infection, Exploit, Malicious Mail, Network Attack, On Demand Scan, Web Threat, Total_Attack_Percentage, Rank Spam, Rank Ransomware, Rank Local Infection, Rank Exploit, Rank Malicious Mail, Rank Network Attack, Rank On Demand Scan, Rank Web Threat]
Index: []

In [56]:
duplicate_count = df.duplicated().sum()
print(f"Total duplicate rows: {duplicate_count}")

Total duplicate rows: 0

In [57]:
# Save cleaned dataset
df.to_csv('formatted_cyber.csv', index=False)

In [59]:
from google.colab import files
files.download("formatted_cyber.csv") # Changed filename to match the saved file